"""
Expand the jurisdiction enums from the DPV Location vocabulary.

The Jurisdiction, SupraNationalJurisdiction and SubnationalJurisdiction enums are
defined by reference to the DPV Location vocabulary (https://w3id.org/dpv/loc). LinkML
generators do not expand such dynamic enums, so this script lists their values in
schema/jurisdictions.yaml. Run it when moving to a new DPV version:

    make expand_jurisdictions
    make compile_pydantic_model
"""

# Standard Library
import argparse
from datetime import date
from pathlib import Path

# Third Party
import rdflib
import yaml
from rdflib.namespace import RDF, SKOS


DPV_VERSION = "2.1"
DEFAULT_SOURCE = (
    f"https://raw.githubusercontent.com/w3c/dpv/master/{DPV_VERSION}/loc/loc.ttl"
)
OUTPUT = Path(__file__).parents[1] / "schema" / "jurisdictions.yaml"

DPV = rdflib.Namespace("https://w3id.org/dpv#")
LOC = "https://w3id.org/dpv/loc#"

# enum name -> (DPV class whose members are its values, description)
ENUMS = {
    "Jurisdiction": (
        "Country",
        "ISO 3166-1 alpha-2 country code, from the DPV Location vocabulary "
        "(https://w3id.org/dpv/loc). Values are members of dpv:Country.",
    ),
    "SupraNationalJurisdiction": (
        "SupraNationalUnion",
        "Supra-national or intergovernmental jurisdiction, from the DPV Location "
        "vocabulary (https://w3id.org/dpv/loc). Values are members of "
        "dpv:SupraNationalUnion (e.g. EU, EEA), plus International.",
    ),
    "SubnationalJurisdiction": (
        "Region",
        "Subnational or regional jurisdiction as an ISO 3166-2 subdivision code "
        "(e.g. US-CA for California, CA-QC for Quebec), from the DPV Location "
        "vocabulary (https://w3id.org/dpv/loc). Values are members of dpv:Region.",
    ),
}

# Values not in DPV Location
EXTRA_VALUES = {
    "SupraNationalJurisdiction": {
        "International": {
            "description": "Explicitly global scope not attributable to any single "
            "country or recognised regional body.",
            "aliases": ["INTERNATIONAL", "international"],
        }
    }
}


def load_values(graph, dpv_class):
    values = {}
    for subject in graph.subjects(RDF.type, DPV[dpv_class]):
        iri = str(subject)
        if not iri.startswith(LOC):
            continue
        code = iri[len(LOC) :]
        label = graph.value(subject, SKOS.prefLabel)
        value = {"meaning": f"dpv-loc:{code}"}
        if label is not None:
            value["description"] = str(label)
        values[code] = value
    return dict(sorted(values.items()))


def build_schema(graph):
    enums = {}
    for name, (dpv_class, description) in ENUMS.items():
        values = load_values(graph, dpv_class)
        values.update(EXTRA_VALUES.get(name, {}))
        enums[name] = {
            "description": description,
            "see_also": ["https://w3id.org/dpv/loc"],
            "enum_uri": f"dpv:{dpv_class}",
            "permissible_values": values,
        }
    return {
        "id": "https://w3id.org/ai-atlas-nexus/jurisdictions",
        "name": "jurisdictions",
        "description": (
            f"Jurisdiction codes from the DPV Location vocabulary, version {DPV_VERSION}. "
            "Generated by util/expand_jurisdictions.py; do not edit by hand."
        ),
        "imports": ["linkml:types"],
        "prefixes": {
            "linkml": "https://w3id.org/linkml/",
            "nexus": "https://w3id.org/ai-atlas-nexus/",
            "dpv": "https://w3id.org/dpv#",
            "dpv-loc": LOC,
        },
        "default_prefix": "nexus",
        "enums": enums,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[1])
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help="URL or path of the DPV Location vocabulary in Turtle (default: DPV %(default)s)",
    )
    parser.add_argument("--output", default=str(OUTPUT))
    args = parser.parse_args()

    graph = rdflib.Graph()
    graph.parse(args.source, format="turtle")
    schema = build_schema(graph)

    header = (
        f"# Generated by src/ai_atlas_nexus/ai_risk_ontology/util/expand_jurisdictions.py\n"
        f"# from {args.source} on {date.today().isoformat()}. Do not edit by hand.\n"
    )
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(schema, f, sort_keys=False, allow_unicode=True, width=120)

    for name in ENUMS:
        print(f"{name}: {len(schema['enums'][name]['permissible_values'])} values")


if __name__ == "__main__":
    main()
